services:
  ceryx:
    volumes:
      - test_certificates:/usr/local/share/certificates

  test:
    build:
      context: ./ceryx
      dockerfile: Dockerfile.test
    environment:
      CERYX_API_URL: "http://api:${CERYX_API_PORT:-5555}"
    volumes:
      - ./ceryx:/usr/src/app
      - test_certificates:/usr/local/share/certificates
    depends_on:
      - ceryx
      - api

volumes:
  test_certificates:
