version: '3.7'

x-common-dev-settings:
  &common-dev-settings
  CERYX_DEBUG: ${CERYX_DEBUG:-true}

services:
  ceryx:
    build: ./ceryx
    volumes:
      - ./ceryx/nginx/conf:/usr/local/openresty/nginx/conf
      - ./ceryx/nginx/lualib:/usr/local/openresty/nginx/lualib
      - ./ceryx/static:/etc/ceryx/static
    ports:
      - ${CERYX_EXTERNAL_PORT:-80}:80
      - ${CERYX_EXTERNAL_SSL_PORT:-443}:443
    environment:
      <<: *common-dev-settings
      CERYX_DOCKERIZE_EXTRA_ARGS: ""

