version: '3.7'

x-common-settings:
  &common-settings
  CERYX_DEBUG: ${CERYX_DEBUG:-false}

services:
  ceryx:
    build: ./ceryx
    image: localhost:5000/ceryx:latest
    ports:
      - ${CERYX_EXTERNAL_PORT:-80}:80
    environment:
      <<: *common-settings
      CERYX_DOCKERIZE_EXTRA_ARGS: -no-overwrite
    command:
      - usr/local/openresty/bin/openresty
      - -g
      - daemon off;
